version: '3'
services:
  db:
    image: postgres:11.2
    ports:
      - '5432:5432'
    volumes:
      - postgresql-data:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/awesome_interview_scheduler
      - bundle_path:/bundle
    environment:
      - BUNDLE_PATH=/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  bundle_path:
    driver: local
  postgresql-data:
    driver: local